### PR TITLE
Property with name `$ref` should not be considered a reference. Fixes #37.

### LINKED ISSUE #37: Property with name `$ref` is considered a reference and swagger specs are not validated
Swagger Specification v 2.0 defines a `$ref` property. Json Guard consider it a reference. It's not.

How to reproduce.

composer.json

```
{
    "require": {
        "league/json-guard": "^0.3.2",
        "symfony/yaml": "^3.1"
    }
}
```

PHP Testing code:
```
<?php

include __DIR__ . '/vendor/autoload.php';

$deref  = new League\JsonGuard\Dereferencer();
$schema = $deref->dereference(
    'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json#'
);

// all below should validate successfully
// all are taken from https://rebilly.github.io/ReDoc/
$specs = [
    'https://rebilly.github.io/ReDoc/swagger.yaml',
    'https://api.apis.guru/v2/specs/instagram.com/1.0.0/swagger.yaml',
    'https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/swagger.yaml',
    'https://api.apis.guru/v2/specs/data2crm.com/1/swagger.yaml',
    'https://api.apis.guru/v2/specs/graphhopper.com/1.0/swagger.yaml'
];
$allValid = true;
foreach ($specs as $spec) {
    $data      = \Symfony\Component\Yaml\Yaml::parse(file_get_contents($spec));
    $data      = json_decode(json_encode($data));
    $validator = new League\JsonGuard\Validator($data, $schema);

    if ($validator->fails()) {
        echo "Swagger Specification `{$spec}` is not valid.\n";
        /** @var \League\JsonGuard\ValidationError $error */
        foreach ($validator->errors() as $error) {
            echo sprintf(" - [%s] (%s) %s\n", $error->getPointer(), $error->getCode(), $error->getMessage());
        }
        $allValid = false;
    }
}
if ($allValid) {
    echo "All Swagger Specifications are valid.\n\n";
}

```
The code above should run without problems. Swagger spec is well known and those specs are valid. You can test them on http://bigstickcarpet.com/swagger-parser/www/index.html .

At first I tried to change the line 176 of `League\JsonGuard\Dereferencer` from

`if ($this->isRef($attribute)) {`

to

`if ($this->isRef($attribute) && is_string($parameter)) {`

which I think is the correct way to go. Then I started getting an `InvalidArgumentException` with message `Invalid JSON: Syntax error` at `/vendor/league/json-guard/src/functions.php:18`.

### PR DESCRIPTION
**Pull request by ribeiropaulor**
Fixes #37 . Now the value of the attribute must be a string to be considered an reference (`$ref`).

### CODE REVIEW

File: src/Dereferencer.php [hunk 1]
```diff
@@ -207,12 +207,13 @@ private function pathPush($path, $segment)
 
     /**
      * @param string $attribute
+     * @param mixed $attribute_value
      *
      * @return bool
      */
-    private function isRef($attribute)
+    private function isRef($attribute, $attribute_value)
```
Comment (yuloh) [inline src/Dereferencer.php]: Can you make this `$attributeValue`? Thanks!
